version: "2"
services: 
  db:
    image: mongo:6.0
    restart: always
    volumes:
      - ~/mongo:/data/db
    container_name: nlp-processor-mongo
    networks:
      - nlp-processor-network
    ports:
      - "27017:27017"
    env_file:
      - .env
  
  redis:
    container_name: nlp-processor-redis
    image: "redis:alpine"
    command: --port 6379
    expose:
      - 6379
    networks:
      - nlp-processor-network
    ports:
      - '6379:6379'

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: story-forge-api
    tty: true
    stdin_open: true
    networks:
      - nlp-processor-network
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on: 
      - db
      - redis
    ports:
      - "8080:8080"

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: story-forge-celery
    tty: true
    stdin_open: true
    command: celery -A celery_app.celery worker --loglevel=info
    networks:
      - nlp-processor-network
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on: 
      - db
      - redis
    ports:
      - "8081:8081"

networks:
  nlp-processor-network:
    driver: bridge